networks:
  dev:
    driver: bridge

services:
  dummbapi:
    image: augerrr/dummbapi:1.0.0
    build:
      context: ./DummbAPI
      dockerfile: Dockerfile           
    container_name: dummbapi-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=DummyDB;Username=postgres;Password=8051396
    ports:
      - "5000:8080"
      - "5001:8081"
    volumes:
      - ~/.aspnet/https:/https:ro
    depends_on:
      - db
    networks:
      - dev
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=8051396
      - POSTGRES_DB=DummyDB
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev 
volumes:
  app_data: