services:
  dummbapi:
    platform: linux/amd64   
    image: augerrr/dummbapi:latest
    container_name: dummbapi-service
    environment:
      - ASPNETCORE_ENVIRONMENT=Release
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=DummyDB;Username=postgres;Password=8051396
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - dev
  db:
    image: postgres:latest
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=8051396
      - POSTGRES_DB=DummyDB
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - app_data:/var/lib/postgresql/data
    networks:
      - dev 

volumes:
  app_data:

networks:
  dev:
    driver: bridge  