version: '3.8'

services:
  api:
    image: augerrr/dummbapi:latest  # Pull from Docker Hub
    container_name: dotnet-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Port=5432;Database=DummyDB;Username=postgres;Password=8051396
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=DummyDB
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=8051396
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
